on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: GoReleaser build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.x'
        id: go

      - name: run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --rm-dist -p 2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
